import Foundation
let usesRussian = !CommandLine.arguments.contains("--english") && Locale.preferredLanguages.first?.hasPrefix("ru") == true
func L(_ text: String) -> String { usesRussian ? text : translations[text] ?? text }
private let translations = [
"Минимум два модификатора, включая ⌘ или ⌃. Esc — отмена записи.": "Use at least two modifiers, including ⌘ or ⌃. Esc cancels recording.",
"Компактная карточка результата":"Compact result card", "Сканировать экран":"Scan screen", "Настройки…":"Settings…", "Из буфера обмена":"Read clipboard image", "Завершить ScreenQR":"Quit ScreenQR", "Сканировать QR-код":"Scan QR code", "Открыть изображение…":"Open image…", "Выход":"Quit", "Сочетание занято":"Shortcut unavailable",
"Выберите другое сочетание в настройках. Сканирование по значку продолжает работать.":"Choose a different shortcut in Settings. The menu bar icon still works.",
"ScreenQR — QR-коды с экрана":"ScreenQR — QR codes from your screen", "QR уже на компьютере?":"QR code on your screen?",
"Нажмите значок QR в строке меню, выделите код и откройте ссылку. Своё сочетание клавиш можно назначить в настройках. Правый клик по значку открывает остальные действия.":"Click the menu bar QR icon, select the code and inspect the link. Set a shortcut in Settings. Right-click the icon for more actions.",
"Распознавание работает на Mac. Изображения не отправляются в интернет и не сохраняются. Доступ к экрану понадобится только для сканирования экрана.":"Recognition runs on your Mac. Images are never uploaded or saved. Screen access is needed only for screen scanning.",
"Сканировать QR на экране":"Scan QR on screen", "Настройки и горячая клавиша…":"Settings and keyboard shortcut…", "Дополнительные способы — картинка и буфер обмена — доступны по правому клику на значке.":"For images and clipboard, right-click the menu bar icon.",
"Не удалось получить снимок экрана":"Could not capture your screen", "Разрешите ScreenQR запись экрана в Системных настройках. Приложение распознаёт QR локально, не записывает звук и не сохраняет снимки. После выдачи доступа перезапустите ScreenQR.":"Allow ScreenQR in System Settings → Privacy & Security → Screen Recording. Recognition is local; audio is not recorded and screenshots are not saved. Restart ScreenQR after granting access.",
"Открыть настройки доступа":"Open permission settings", "Позже":"Later", "В буфере нет изображения":"No image in the clipboard", "Скопируйте картинку с QR-кодом или выделите код прямо на экране.":"Copy an image with a QR code, or select the code directly on your screen.",
"Не удалось прочитать изображение":"Could not read the image", "Попробуйте файл PNG, JPEG или HEIC.":"Try a PNG, JPEG or HEIC image.", "Распознаём QR…":"Reading QR…", "Проверяем выделенную область на вашем Mac…":"Checking the selected area on your Mac…", "Отмена":"Cancel", "Не удалось распознать QR":"Could not read the QR code", "Попробуйте другое изображение или выделите область снова.":"Try another image or select the area again.",
"Данные сети Wi-Fi":"Wi-Fi network", "Контакт":"Contact", "Электронная почта":"Email", "Телефон":"Phone", "Текст или данные QR":"Text or QR data", "QR-код не найден":"No QR code found", "Попробуйте увеличить изображение и выделить код целиком, оставив немного пространства вокруг.":"Enlarge the code and select all of it, including a small margin around the edges.",
"Выделить снова":"Select again", "Закрыть":"Close", "QR распознан":"QR code found", "Найдено QR-кодов":"QR codes found", "Показать полный адрес":"Show full address", "Открыть в браузере":"Open in browser", "Скопировать":"Copy", "Скопировано ✓":"Copied ✓", "Не удалось открыть ссылку":"Could not open the link", "Скопируйте адрес и вставьте его в браузер.":"Copy the address and paste it into your browser.",
"Настройки ScreenQR":"ScreenQR settings", "Горячая клавиша":"Keyboard shortcut", "Не назначена":"Not assigned", "Назначить своё сочетание…":"Record a shortcut…", "Отключить сочетание":"Disable shortcut", "Запускать при входе в систему":"Launch at login", "Снимки и результаты не сохраняются на диск. Ссылки открываются только по вашему нажатию.":"Screenshots and results are not saved to disk. Links open only when you click Open.",
"Открыть изображение / перетащить файл":"Open an image / drop a file", "Нажмите сочетание · Esc — отмена":"Press a shortcut · Esc to cancel", "Записать своё сочетание…":"Record a shortcut…", "Это сочетание недоступно. Выберите другое":"Unavailable combination. Try another", "Занято системой. Выберите другое сочетание":"Used by macOS. Try another", "клавиша":"key", "Назначить другое сочетание…":"Record another shortcut…", "Не удалось изменить автозапуск":"Could not change login startup", "Переместите приложение в Applications и проверьте Системные настройки → Основные → Объекты входа.":"Move ScreenQR to Applications and check System Settings → General → Login Items.", "Выделите QR-код · Esc — отмена":"Select the QR code · Esc to cancel", "Перетащите сюда изображение с QR":"Drop a QR image here"
]
